import fs from 'fs';
import type { z } from 'zod';
import { alfredConfigSchema } from '../schemas/workflow-config';

import { Command } from 'commander';
import { cliSchema } from '../schemas/cli-schema';
import path from 'path';

/**
 *
 * @returns { string } Path to config.json, generated by makefile or automated build script.
 */
export const getConfigPath = (): string => path.join(__dirname, '../../', 'config.json');

/**
 *
 * @returns
 */
export const getConfig = (): z.infer<typeof alfredConfigSchema> => {
  const configPath = getConfigPath();
  try {
    const rawData = fs.readFileSync(configPath, 'utf-8');
    const parsedData = JSON.parse(rawData);
    const config = alfredConfigSchema.parse(parsedData);
    return config;
  } catch (error) {
    console.error('Error loading or parsing config file:', error);
    throw new Error('Failed to load configuration.');
  }
};

/**
 *
 * @param token { string }
 * @returns { boolean } Whether the provided GitHub token is valid.
 */
export const isValidGithubToken = (token: string | undefined): boolean => {
  // GitHub token length varies, but generally >= 40 chars and start with "ghp_"
  return undefined !== token && token.trim().length >= 40 && token.startsWith('ghp_');
};

/**
 *
 * @param key { string }
 * @returns { boolean } Whether the provided OpenAI API key is valid.
 */
export const isValidOpenAIKey = (key: string | undefined): boolean => {
  // API key length varis, but generally exceed 40 chars and start with "sk-"
  return undefined !== key && key.trim().length >= 40 && key.startsWith('sk-');
};

/**
 *
 * @param key { string }
 * @returns { boolean } Whether the provided API key is valid.
 */
export const isValidAPIKey = (key: string | undefined): boolean => {
  return undefined !== key && key.trim().length >= 20;
};

export const getCLIParams = (): z.infer<typeof cliSchema> => {
  const program = new Command();
  program.option('--action <string>', 'CLI action to perform', 'serverStatus');
  program.option('--argument <string>', 'Argument for the action', '');

  // Allow for help text
  const sep = '-'.repeat(50);
  const codeSamples = [
    'node dist/cli.js --action home --argument "home"',
    'node dist/cli.js --action notify --argument "Hey there"',
    'node dist/cli.js --action terminal-command --argument "ls -la"',
    'node dist/cli.js --action kill-server',
    'node dist/cli.js --action restart-server',
  ];
  program.on('--help', () => {
    console.log('');
    console.log(sep);
    console.log('💡 Example call:');
    console.log(codeSamples.map((sample) => `   ${sample}`).join('\n'));
    console.log(sep);
  });

  program.parse(process.argv);
  return cliSchema.parse(program.opts());
};
